/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Apikey {
  configId: string;
  createdAt: Timestamp;
  enabled: boolean | null;
  expiresAt: Timestamp | null;
  id: string;
  key: string;
  lastRefillAt: Timestamp | null;
  lastRequest: Timestamp | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rateLimitEnabled: boolean | null;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  referenceId: string;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number | null;
  start: string | null;
  updatedAt: Timestamp;
}

export interface ClickEvents {
  browser: string | null;
  clickedAt: Generated<Timestamp>;
  country: string | null;
  device: string | null;
  id: Generated<string>;
  isBot: Generated<boolean>;
  linkId: string;
  os: string | null;
  referrerDomain: string | null;
}

export interface DomainBlocklist {
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  disabledAt: Timestamp | null;
  domain: string;
  id: Generated<string>;
  reason: string | null;
}

export interface LinkAuditLogs {
  action: string;
  actorApiKeyId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  linkId: string;
  newValue: Json | null;
  previousValue: Json | null;
  userId: string | null;
}

export interface Links {
  code: string;
  createdAt: Generated<Timestamp>;
  createdViaApiKeyId: string | null;
  deletedAt: Timestamp | null;
  destinationUrl: string;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  status: Generated<string>;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface UserProfiles {
  createdAt: Generated<Timestamp>;
  role: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  apikey: Apikey;
  clickEvents: ClickEvents;
  domainBlocklist: DomainBlocklist;
  linkAuditLogs: LinkAuditLogs;
  links: Links;
  session: Session;
  user: User;
  userProfiles: UserProfiles;
  verification: Verification;
}
