/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ClickEvents {
  browser: string | null;
  clickedAt: Generated<Timestamp>;
  country: string | null;
  device: string | null;
  id: Generated<string>;
  isBot: Generated<boolean>;
  linkId: string;
  os: string | null;
  referrerDomain: string | null;
}

export interface DomainBlocklist {
  createdAt: Generated<Timestamp>;
  createdByUserId: string;
  disabledAt: Timestamp | null;
  domain: string;
  id: Generated<string>;
  reason: string | null;
}

export interface LinkAuditLogs {
  action: string;
  actorApiKeyId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  linkId: string;
  newValue: Json | null;
  previousValue: Json | null;
  userId: string | null;
}

export interface Links {
  code: string;
  createdAt: Generated<Timestamp>;
  createdViaApiKeyId: string | null;
  deletedAt: Timestamp | null;
  destinationUrl: string;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  status: Generated<string>;
  title: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface UserProfiles {
  createdAt: Generated<Timestamp>;
  role: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DB {
  clickEvents: ClickEvents;
  domainBlocklist: DomainBlocklist;
  linkAuditLogs: LinkAuditLogs;
  links: Links;
  userProfiles: UserProfiles;
}
