/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLinksRouteImport } from './routes/dashboard.links'
import { Route as DashboardLinksNewRouteImport } from './routes/dashboard.links.new'
import { Route as DashboardLinksIdRouteImport } from './routes/dashboard.links.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksNewRoute = DashboardLinksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardLinksRoute,
} as any)
const DashboardLinksIdRoute = DashboardLinksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardLinksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/links': typeof DashboardLinksRouteWithChildren
  '/dashboard/links/$id': typeof DashboardLinksIdRoute
  '/dashboard/links/new': typeof DashboardLinksNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/links': typeof DashboardLinksRouteWithChildren
  '/dashboard/links/$id': typeof DashboardLinksIdRoute
  '/dashboard/links/new': typeof DashboardLinksNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/links': typeof DashboardLinksRouteWithChildren
  '/dashboard/links/$id': typeof DashboardLinksIdRoute
  '/dashboard/links/new': typeof DashboardLinksNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/links'
    | '/dashboard/links/$id'
    | '/dashboard/links/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/links'
    | '/dashboard/links/$id'
    | '/dashboard/links/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/links'
    | '/dashboard/links/$id'
    | '/dashboard/links/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links/new': {
      id: '/dashboard/links/new'
      path: '/new'
      fullPath: '/dashboard/links/new'
      preLoaderRoute: typeof DashboardLinksNewRouteImport
      parentRoute: typeof DashboardLinksRoute
    }
    '/dashboard/links/$id': {
      id: '/dashboard/links/$id'
      path: '/$id'
      fullPath: '/dashboard/links/$id'
      preLoaderRoute: typeof DashboardLinksIdRouteImport
      parentRoute: typeof DashboardLinksRoute
    }
  }
}

interface DashboardLinksRouteChildren {
  DashboardLinksIdRoute: typeof DashboardLinksIdRoute
  DashboardLinksNewRoute: typeof DashboardLinksNewRoute
}

const DashboardLinksRouteChildren: DashboardLinksRouteChildren = {
  DashboardLinksIdRoute: DashboardLinksIdRoute,
  DashboardLinksNewRoute: DashboardLinksNewRoute,
}

const DashboardLinksRouteWithChildren = DashboardLinksRoute._addFileChildren(
  DashboardLinksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardLinksRoute: typeof DashboardLinksRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLinksRoute: DashboardLinksRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
